name: Headless Mac + VNC Setup

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  setup:
    runs-on: [self-hosted, macos, arm64]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Homebrew if missing
        run: |
          if ! command -v brew >/dev/null 2>&1; then
            echo "Homebrew not found, installing..."
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $GITHUB_ENV
            eval "$(/opt/homebrew/bin/brew shellenv)"
          else
            echo "Homebrew already installed"
          fi

      - name: Install BetterDummy (Virtual Display)
        run: |
          brew install --cask betterdummy || echo "BetterDummy already installed"
          open -a BetterDummy
          sleep 5  # give it a few seconds to initialize

      - name: Enable Screen Sharing (VNC)
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -restart -agent -privs -all
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -clientopts -setvnclegacy -vnclegacy yes \
            -configure -clientopts -setvncpw -vncpw "YOUR_VNC_PASSWORD"
          echo "VNC ready! Connect to vnc://$RUNNER_IP"
